name: olist-bq
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      # --- Orchestration ---
      - dagster
      - dagster-webserver
      - dagster-dbt
      
      # --- Transformation & Ingestion ---
      - dbt-bigquery
      - meltano
      
      # --- High-Speed BigQuery Data Access (FIXED) ---
      - google-cloud-bigquery
      - google-cloud-bigquery-storage # <--- Adds the missing module
      - grpcio                        # <--- Required for high-speed transfer
      - pyarrow                       # <--- Required for fast DataFrame conversion
      - pandas-gbq
      
      # --- Quality & Analysis ---
      - great-expectations  # Required for your ge_raw_order_items.py script
      - jupyter
      - dbterd  # er diagram
      - pandas
      - numpy
      - python-dotenv

      # --- Dashboard & Visualization ---
      - streamlit
      - plotly
      - statsmodels
      - matplotlib
      - seaborn