name: "dbt_olist"
version: "1.0.0"
config-version: 2

profile: "dbt_olist" 

# Core Paths
model-paths: ["models"]
seed-paths: ["seeds"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# NEW: Required by dbt-expectations for 'recent_data' tests
vars:
  dbt_date:time_zone: "America/Sao_Paulo" # Sets timezone for Olist Brazil data

# Model Configurations
models:
  dbt_olist: 
    staging:
      +materialized: view
    intermediate:
      +materialized: table      
    marts:
      +materialized: table

# Seed Configurations
seeds:
  dbt_olist:
    patch_missing_geolocations:
      +column_types:
        zip_code_prefix: string
